// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yagaeuoepdoblpboioeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZ2FldW9lcGRvYmxwYm9pb2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTc4MTAsImV4cCI6MjA4NDU3MzgxMH0.lSJyZpSt8JkyjduGQtuL_2gGqD3nNfKzDOO9wmq_yx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});